# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 462c114cfdf7a4938ba715e11724e8321179cf1c3938ac09852ed503b1bc5f6e3dfe70ac95111491395b93e448fcd3d1ece209b9b993a8b6c920e97652f84506

test:
  secret_key_base: 6f4eeb13b36cbc2b88517fba49b629e6cce3fffe20364ccce7f6d6bd50e28d228c05d0fe8aaefef0c3363cd7e7ec46986ea9c667821cfc96a5282c7c3250055c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
